package com.example.feature.chat.database

import androidx.room.RoomDatabaseConstructor

// implementation generated by Gradle plugin
expect object ChirpChatDatabaseConstructor : RoomDatabaseConstructor<ChirpChatDatabase> {
    override fun initialize(): ChirpChatDatabase
}